protocols:
  - name: standard_30W_30s
    power_W: 30.0
    duration_s: 30.0
  - name: hpsd_50W_10s
    power_W: 50.0
    duration_s: 10.0
  - name: vhpsd_90W_4s
    power_W: 90.0
    duration_s: 4.0
