protocols:
  - name: standard_30W_30s
    power_W: 30
    duration_s: 30
    use_controller: false

  - name: hpsd_50W_10s
    power_W: 50
    duration_s: 10
    use_controller: false

  - name: vhpsd_90W_4s_fixed
    power_W: 90
    duration_s: 4
    use_controller: false

  - name: vhpsd_90W_4s_controlled
    power_W: 90
    duration_s: 4
    use_controller: true
